version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fl4shr21@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "82:80"
    depends_on:
      - db

volumes:
  pgdata: