version: '3'
services:
  api:
    image: fl4shr/fastapi_guitars_api-api:latest
    entrypoint: ["sh", "-c", "poetry run alembic upgrade head && poetry run ./src/run"]
    restart: always
    ports:
      - "${APP_PORT}:8000"
    environment:
      -DB_NAME=${DB_NAME}
      -DB_USER=${DB_USER}
      -DB_PASS=${DB_PASS}
      -DB_HOST=db
      -DB_PORT=${DB_PORT}
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "82:80"
    depends_on:
      - db

volumes:
  pgdata: