services:
  api:
    image: fl4shr/fastapi_guitars_api-api:latest
    entrypoint: ["sh", "-c", "poetry run alembic upgrade head && poetry run ./src/run"]
    restart: always
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - DB_NAME=${DB_NAME:-postgres}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-password}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-5432}
    depends_on:
      - db
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "82:80"
    depends_on:
      - db

volumes:
  pgdata: