"""add guitars and brands tables

Revision ID: ef487814c8ad
Revises: 2a2e8c3dcb8f
Create Date: 2025-01-10 14:51:10.858173

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ef487814c8ad"
down_revision: Union[str, None] = "2a2e8c3dcb8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
