"""add guitars and brands tables

Revision ID: 4b5a9ba3211a
Revises: ef487814c8ad
Create Date: 2025-01-10 14:54:36.798415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5a9ba3211a'
down_revision: Union[str, None] = 'ef487814c8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
