"""add guitars and brands tables

Revision ID: 6f3498afb717
Revises: 4b5a9ba3211a
Create Date: 2025-01-10 14:56:16.611985

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "6f3498afb717"
down_revision: Union[str, None] = "4b5a9ba3211a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
