"""Initial migrations

Revision ID: 78e007dc232f
Revises: 15f67836183e
Create Date: 2025-01-09 18:19:38.645478

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "78e007dc232f"
down_revision: Union[str, None] = "15f67836183e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
