name: CI/CD

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/fastapi_guitars_api-api:latest
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1 
      - name: Installing Requirements
        run: |
          poetry install --no-root
      - name: Run flake8
        run: |
          poetry run flake8 .
      - name: Run black
        run: |
          poetry run black . --check
      - name: docker-compose up
        run: |
          docker compose up -d
      - name: Run pytest
        run: |
          poetry run pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: docker-compose up
        uses: hoverkraft-tech/compose-action@v2.0.1
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .

      


      
