name: CI/CD

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
        continue-on-error: false
      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false
      - name: Build docker-compose
        run: docker-compose build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instaling python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Installing flake8-black and black and pytest with httpx
        run: |
          python -m pip install --upgrade pip
          pip install flake8-black black pytest-asyncio httpx
      - name: Run flake8
        run: |
          flake8 .
      - name: Run black
        run: |
          black . --check
      - name: Run tests
        run: |
          docker-compose run -rm api poetry runpytest
      


      
