name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Requirements
        run: poetry install --no-root && poetry shell
      - name: Run flake8
        run: |
          flake8 .
      - name: Run black
        run: |
          black . --check
      - name: Run tests
        run: |
          pytest
      


      
