name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_on:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instaling python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Installing flake8-black and black
        run: |
          python -m pip install --upgrade pip
          pip install flake8-black black
      - name: Run flake8
        run: |
          flake8 .
      - name: Run black
        run: |
          black . --check


      
