name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Instaling python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Installing flake8-black and black and pytest with httpx
        run: |
          python -m pip install --upgrade pip
          pip install flake8-black black pytest-asyncio httpx
      - name: Run flake8
        run: |
          flake8 .
      - name: Run black
        run: |
          black . --check
      - name: Run tests
        run: |
          pytest
      


      
